name: bioprov
channels:
  - salilab
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - argon2-cffi=20.1.0
  - async_generator=1.10
  - attrs=20.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.1
  - bleach=3.2.1
  - brotlipy=0.7.0
  - ca-certificates=2020.6.20
  - certifi=2020.6.20
  - cffi=1.14.3
  - chardet=3.0.4
  - cryptography=3.1.1
  - decorator=4.4.2
  - defusedxml=0.6.0
  - entrypoints=0.3
  - idna=2.10
  - importlib-metadata=2.0.0
  - importlib_metadata=2.0.0
  - ipykernel=5.3.4
  - ipython=5.8.0
  - ipython_genutils=0.2.0
  - jinja2=2.11.2
  - json5=0.9.5
  - jsonschema=3.2.0
  - jupyter_client=6.1.7
  - jupyter_core=4.6.3
  - jupyterlab=2.2.8
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=1.2.0
  - ld_impl_linux-64=2.35
  - libcxx=11.0.0
  - libcxxabi=11.0.0
  - libffi=3.2.1
  - libgcc-ng=9.3.0
  - libgomp=9.3.0
  - libsodium=1.0.18
  - libstdcxx-ng=9.3.0
  - markupsafe=1.1.1
  - mistune=0.8.4
  - nbclient=0.5.1
  - nbconvert=6.0.7
  - nbformat=5.0.8
  - ncurses=6.2
  - nest-asyncio=1.4.1
  - notebook=6.1.4
  - openssl=1.1.1h
  - packaging=20.4
  - pandoc=2.11.0.2
  - pandocfilters=1.4.2
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=20.2.3
  - prodigal=2.6.3
  - prometheus_client=0.8.0
  - prompt_toolkit=1.0.15
  - ptyprocess=0.6.0
  - pycparser=2.20
  - pygments=2.7.1
  - pyopenssl=19.1.0
  - pyparsing=2.4.7
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - python=3.7.8
  - python-dateutil=2.8.1
  - python_abi=3.7
  - pyzmq=19.0.2
  - readline=8.0
  - requests=2.24.0
  - send2trash=1.5.0
  - setuptools=49.6.0
  - simplegeneric=0.8.1
  - six=1.15.0
  - sqlite=3.33.0
  - terminado=0.9.1
  - testpath=0.4.4
  - tk=8.6.10
  - tornado=6.0.4
  - traitlets=5.0.5
  - urllib3=1.25.10
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.35.1
  - xz=5.2.5
  - zeromq=4.3.3
  - zipp=3.3.1
  - zlib=1.2.11
  - pip:
    - alabaster==0.7.12
    - appdirs==1.4.4
    - babel==2.8.0
    - bioprov==0.1.7
    - biopython==1.78
    - black==20.8b1
    - click==7.1.2
    - coolname==1.1.0
    - coverage==5.3
    - coveralls==2.1.2
    - dataclasses==0.6
    - docopt==0.6.2
    - docutils==0.16
    - imagesize==1.2.0
    - iniconfig==1.1.1
    - isodate==0.6.0
    - lxml==4.5.2
    - markdown-it-py==0.5.5
    - mypy-extensions==0.4.3
    - myst-parser==0.12.10
    - networkx==2.5
    - numpy==1.19.2
    - pandas==1.1.3
    - pathspec==0.8.0
    - pluggy==0.13.1
    - prov==1.5.3
    - py==1.9.0
    - pydot==1.4.1
    - pytest==6.1.1
    - pytest-cov==2.10.1
    - pytz==2020.1
    - pyyaml==5.3.1
    - rdflib==5.0.0
    - regex==2020.10.15
    - snowballstemmer==2.0.0
    - sphinx==3.2.1
    - sphinx-rtd-theme==0.5.0
    - sphinxcontrib-applehelp==1.0.2
    - sphinxcontrib-devhelp==1.0.2
    - sphinxcontrib-htmlhelp==1.0.3
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==1.0.3
    - sphinxcontrib-serializinghtml==1.1.4
    - toml==0.10.1
    - tqdm==4.50.2
    - typed-ast==1.4.1
    - typing-extensions==3.7.4.3
