name: bioprov
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - biopython
  - coolname
  - coveralls
  - dataclasses
  - pandas
  - prodigal
  - prov
  - provstore-api
  - pydot
  - pytest
  - pytest-cov
  - tqdm
  - tinydb